# Generated by Django 4.2 on 2024-02-10 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number format: '(+)ccxxxxxxxxxx' with 8 to 15 digits.", regex="'^\\+\\d{8,15}$")]),
        ),
    ]
