# Generated by Django 4.2 on 2024-02-10 19:05

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_date_of_birth_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='12345678', max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number format: '(+)ccxxxxxxxxxx' with 8 to 15 digits.", regex='^\\+?\\d{8,15}$')]),
            preserve_default=False,
        ),
    ]
