# Generated by Django 4.0.6 on 2024-02-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id']},
        ),
    ]
